# Generated by Django 2.0.3 on 2019-01-30 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('report_type', models.CharField(choices=[('AN', 'annual'), ('MO', 'monthly'), ('WE', 'weekly')], max_length=2)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('created_by', models.CharField(max_length=30)),
                ('resolved_by', models.CharField(blank=True, max_length=30, null=True)),
                ('resolved_on', models.DateField(blank=True, null=True)),
                ('is_resolved', models.BooleanField(default=False)),
            ],
        ),
    ]
